name: iterable_dropdown
description: "A Flutter dropdown that works on iterable instead of lists. It also has multi select functionality"
version: 2.0.4
repository: https://github.com/simranss/flutter_iterable_dropdown

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - dropdown
  - multiselect
  - iterable
  - multiple

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# The following section is specific to Flutter packages.
flutter: null

screenshots:
  - description: "Example screenshot 1"
    path: screenshots/customisations.png
